services:
  spring:
    build: .
    container_name: paletto
    networks:
      - web-net
    ports:
      - 8080:8080
  postgres:
    image: postgres:15
    container_name: my_postgres
    networks:
      - web-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: clue1234
      POSTGRES_PASSWORD: clue52025
      POSTGRES_DB: clue
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: my_redis
    networks:
      - web-net
    ports:
      - "6379:6379"

networks:
  web-net:
    external: true