services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: clue1234
      POSTGRES_PASSWORD: clue52025
      POSTGRES_DB: clue
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

<<<<<<< HEAD
  
=======
  redis:
    image: redis
    container_name: my_redis
    ports:
      - "6379:6379"
>>>>>>> feat/#2
