spring:
  application:
    name: CLUE-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/clue
    username: clue1234
    password: clue52025
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  address: 0.0.0.0
  port: 8080