spring:
  application:
    name: CLUE-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/clue
    username: clue1234
    password: clue52025
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

server:
  address: 0.0.0.0
  port: 8080

app:
  cors:
    allowed-origins: http://0.0.0.0:3000